theme: jekyll-theme-cayman

title: Dave Innovation Site
description: An Innovative Innovation Website for Innovative Innovators.

show_downloads: "false"

github:
  zip_url: https://twitter.com/home
  another_url: https://facebook.com
